port:
  server: 8081
  grpcServer: 10010
messageInfo:
  APIAccount: "8a216da874af5fff0174b45a5926026f"
  APIToken: "4b923369078c476d997901df5c77598f"
  AppID: "8a216da874af5fff0174b45a5a2b0276"
  TemplateID: "1"
dataSource:
  MySQL:
    driverName: "mysql"
    host: "127.0.0.1"
    port: "3306"
    database: "project_news"
    username: "root"
    password: "Zz7722559"
    charset: "utf8"
    loc: "Local"
  MongoDB:
    driverName: "mongodb"
    host: "127.0.0.1"
    port: "27017"
    database: "model"
    timeout: 10